### ISSUE TITLE
Bug in List View

### ISSUE THREAD

**Issue by daknob** [DaKnOb/TorPaste#55]
Pull Request #54 introduced a bug that causes this:

```
[2016-11-02 12:30:22,130] ERROR in app: Exception on /list [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/torpaste/torpaste.py", line 137, in list
    status, data, code = logic.get_paste_listing(config, listFilters)
  File "/torpaste/logic.py", line 134, in get_paste_listing
    paste_list = b.get_all_paste_ids(filters)
  File "/torpaste/backends/filesystem.py", line 257, in get_all_paste_ids
    if get_paste_metadata_value(p, k) != v:
  File "/torpaste/backends/filesystem.py", line 214, in get_paste_metadata_value
    if get_paste_metadata(paste_id)[key]:
KeyError: 'visibility'
```

when listing the pastes from a `docker` container ran with:

```bash
docker run -d -p 80:80 -v /pastes:/torpaste/pastes --name torpaste --restart=always daknob/torpaste
```

As you can see, the optional variable `TP_ENABLED_PASTE_VISIBILITIES` is missing.

**Comment by daknob** [comment]
Okay, so the bug is that the `visibility` metadata is not available to all pastes, for examples the ones from a previous version of TorPaste. I will patch this and assume the `visibility` before is `public`, as always.

**Comment by daknob** [comment]
More specifically it is an issue in the `backend.py` filesystem. Patch coming up soon!

**Comment by j11e** [comment]
S**t, I didn't test this. I don't keep pastes between tests, although I clearly should.

That said, if no `visibility` meta is available, the "default visibility" (the first one in the config'd list of enabled visibilities) should probably be used, consistently with paste creation.

**Comment by daknob** [comment]
@j11e So far I have this:

``` diff
diff --git a/backends/filesystem.py b/backends/filesystem.py
index aa80ca6..40c5f4b 100644
--- a/backends/filesystem.py
+++ b/backends/filesystem.py
@@ -211,9 +211,9 @@ def get_paste_metadata_value(paste_id, key):
              the key wasn't set
     """

-    if get_paste_metadata(paste_id)[key]:
+    try:
         return get_paste_metadata(paste_id)[key]
-    else:
+    except:
         return None
```

however without any more changes, the previous pastes are treated as unlisted:

``` python
if get_paste_metadata_value(p, k) != v:
```

The above `if` is simply not true, since I return `None`.
